
services:
  noted-postgres:
    image: postgres:16-alpine
    container_name: noted-postgres
    environment:
      POSTGRES_DB: noted
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ep543
    ports:
      - "5432:5432"
    volumes:
      - noted_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d noted"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  noted_postgres_data:
